import React from "react";
import ReactDOM from "react-dom";
import ArrowDown from "./lib/components/ArrowDown";

function App() {
  return (
    <div>
      <h1>Pico</h1>
      <p>Icons generated by formulas.</p>
      <p>
        <ArrowDown />
      </p>
    </div>
  );
}

ReactDOM.render(<App />, document.getElementById("root"));
